name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and capture logs
        run: |
          docker build -t vinay1304/flask-registration-app:latest . > build.log 2>&1
        continue-on-error: true

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: docker-build-log
          path: build.log
